# Pre-built image with dependencies already installed
image: lunamoonfang/wtg-php:build-7.2

cache:
  paths:
    - vendor/
    - node_modules/

stages:
  - build
  - test
  - deploy

build_job:
  stage: build

  script:
    # Install Composer and project dependencies.
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar install --no-progress

    # Install Node dependencies.
    - npm install -s

    # Copy over testing configuration.
    - cp .env.testing .env

    # Generate an application key. Re-cache.
    - php artisan key:generate
    - php artisan config:cache

    # Build the assets
    - npm run prod

test_job:
  stage: test

  services:
    - mysql:latest

  variables:
    MYSQL_DATABASE: wiringa
    MYSQL_ROOT_PASSWORD: secret

  script:
    # Run laravel tests
    - php vendor/bin/phpunit --coverage-text --colors=never

deploy_staging_job:
  stage: deploy

  when: manual

  only:
    - release

  script:
    # Install ssh-agent if not already installed
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'

    # Run ssh-agent
    - eval $(ssh-agent -s)

    # Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null

    # Create the SSH directory and give it the right permissions
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

    # Known host checking
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

    # Release to staging
    - vendor/bin/dep deploy staging

deploy_production_job:
  stage: deploy

  when: manual

  only:
    - master

  script:
    # Release to production
    - vendor/bin/dep deploy production