language: php

php:
  - '7.1'

install:
  - npm install
  - composer install --no-interaction

script:
  - npm run prod
  - vendor/bin/phpunit

#deploy:
#  skip_cleanup: true
#  - provider: script
#    script: vendor/bin/dep deploy staging
#    on:
#      branch: task/redesign-and-rewrite