language: php

php:
- 7.0

sudo: false

before_install:
- cp .env.travis .env
- mysql -e 'create database testing;'
- composer self-update
- nvm install 6
- npm i -g yarn

install:
- yarn
- composer install --no-interaction
- php artisan migrate
- travis_retry npm install
- node_modules/.bin/gulp

script: vendor/bin/phpunit

notifications:
    slack:
        rooms:
            secure: lyYw8YwQPqbJdjHMIEoF0Rq1yNlLmVnJsuFUX8p8gJri2e1o+Kg4JbT2/PKzL3q2H0VsKlrCyO3PweNTROH8g911x7QJhKFL3mIXPXytC0HKreXwAe/aQtuvP1nox+4jRBH4YAXWtexevchRttOuIS8ok7DM8r+yn3gxmUE07+XsEirmogth6qW19657l3KgD7DQUMk+jcKsnVu3GAfn4LL2hn+PPm3k5CAjeHz2Euyf95LYR3CAP42891Ss6c5vCoZwL8Adowk7hTXfUfAlHyUOxUrgzNyuTs3yOWB5CDBaDc9iNFuKfqC1/rTKEFl5Tl7lyjP8jMEDXRU3xRdQjqq+mBwnAAnoZ7vuhoyYOKGBAqC8pdB164g+KdMY37OAySZevF27KN4UnW+FP0kD+kCmd9Xn6x4mLrTBjOo357TOmhJQyB5gaEhq3zB+wWGjTpHdkUI+O/+C7VB1zUJ9PL2LBEnf7AOm6GZbDfTDvR96wvzDX1G4QIlNMkR9dYWayZc5R1jybcRmz/td82TG9YDICUm7PrG6Q4r54yz/2VmpoG4r70pw+OoYtBRLG6OCXW5F6JcS61sVx9WEFp2dvL/YdFiNBaWF20Hwbxe2XsO02Jm+RPYwpbm1heeiLiNNM3YDfwhIwCkw1MK+p0xZr+lfEIiOoKVzmhABP57KvAY=

branches:
    only:
        - master
        - production
